[package]
name = "gitsync"
version = "0.1.0"
authors = ["David McKay <david@rawkode.com>"]
edition = "2018"
license = "MIT"
description = "GitOps in Rust"

[dependencies]
actix = "0.10.0-alpha.3"
chrono = "0.4.13"
env_logger = "0.7.1"
futures = "0.3"
git2 = "0.13.8"
log = "0.4.0"
tempdir = "0.3.7"
